/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleTeamRouteImport } from './routes/$locale.team'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale.projects.index'
import { Route as LocaleProjectsSlugRouteImport } from './routes/$locale.projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTeamRoute = LocaleTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsSlugRoute = LocaleProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/team': typeof LocaleTeamRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/team': typeof LocaleTeamRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/team'
    | '/$locale/'
    | '/$locale/projects/$slug'
    | '/$locale/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/team'
    | '/$locale'
    | '/$locale/projects/$slug'
    | '/$locale/projects'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/team'
    | '/$locale/'
    | '/$locale/projects/$slug'
    | '/$locale/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/team': {
      id: '/$locale/team'
      path: '/team'
      fullPath: '/$locale/team'
      preLoaderRoute: typeof LocaleTeamRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/projects'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/$slug': {
      id: '/$locale/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/$locale/projects/$slug'
      preLoaderRoute: typeof LocaleProjectsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleTeamRoute: typeof LocaleTeamRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleProjectsSlugRoute: typeof LocaleProjectsSlugRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleTeamRoute: LocaleTeamRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleProjectsSlugRoute: LocaleProjectsSlugRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
